---
title: "Diamond sizes"
date: 2016-08-25
output: html_document
---

```{r setup, include = FALSE}
library(ggplot2)
library(dplyr)

smaller <- diamonds %>% 
  filter(carat <= 2.5)
```

We have data about `r nrow(diamonds)` diamonds. Only 
`r nrow(diamonds) - nrow(smaller)` are larger than
2.5 carats. The distribution of the remainder is shown
below:

```{r, echo = FALSE}
smaller %>% 
  ggplot(aes(carat)) + 
  geom_freqpoly(binwidth = 0.01)
```

```{r, echo = FALSE}
diamonds %>% ggplot(aes(x =carat))+
  geom_histogram(aes(group = cut, fill = cut)) +
  facet_wrap(~ cut)

```
```{r}
diamonds %>% ggplot(aes(x = carat))+
  geom_histogram(aes(group = color, fill = color)) +
  facet_wrap(~ color)

```
```{r}
smaller %>% ggplot(aes(x =carat))+
  geom_histogram(aes(group = clarity, fill = clarity)) +
  facet_wrap(~ clarity)
```
```{r}
#12.2.1 Exercises
#Compute the rate for table2, and table4a + table4b. You will need to perform four operations:
#Extract the number of TB cases per country per year.
table2 %>% 
  pivot_wider(names_from = type, 
              values_from = count) %>% 
  select(!population) 
#Extract the matching population per country per year.
table2 %>% 
  pivot_wider(names_from = type, 
              values_from = count) %>% 
  select(!cases)
#Divide cases by population, and multiply by 10000.
table2 %>% 
  pivot_wider(names_from = type, 
              values_from = count) %>% 
  mutate(prop = ( cases / population)*10000 )
#Store back in the appropriate place.
#Which representation is easiest to work with? Which is hardest? Why?
#the one widened is much easier to work with to calculated prop
```

```{r}
#12.3.3 Exercises
stocks <- tibble(
  year   = c(2015, 2015, 2016, 2016),
  half  = c(   1,    2,     1,    2),
  return = c(1.88, 0.59, 0.92, 0.17)
)
stocks %>% 
  pivot_wider(names_from = year, values_from = return) %>% 
  pivot_longer(`2015`:`2016`, names_to = "year", values_to = "return")

people <- tribble(
  ~name,             ~names,  ~values,
  #-----------------|--------|------
  "Phillip Woods",   "age",       45,
  "Phillip Woods",   "height",   186,
  "Phillip Woods",   "age",       50,
  "Jessica Cordero", "age",       37,
  "Jessica Cordero", "height",   156
)

#3.What would happen if you widen this table? Why? How could you add a new column to uniquely identify each value?
people %>%
    group_by(name, names) %>% 
    mutate( key = row_number()) %>% 
    pivot_wider(names_from = names, values_from = values)

```




