---
title: "Replicate"
output: html_document
date: "2024-06-25"
---

#Importing packages
```{r}
library(dbplyr)
library(lubridate)
library(tidyverse)
```

```{r}
setwd("C:/Users/suvedei/Desktop/Immigration paper Replica")
df <- read.csv("google_trend_search.csv", header = FALSE, col.names = c("ym", "report", "crime", "welfare"))
#colnames(df) <- c("search")
df <- df[-c(1, 2), ] %>%  mutate(ym = ym(ym), report = as.numeric(report), crime = as.numeric(crime), welfare = as.numeric(welfare)) %>% filter(ym < ym("2020-01"))
df<- df %>% mutate( president = case_when(
  ym < ym("2009-01") ~ "Bush" ,
  ym < ym("2017-01") ~ "Obama" ,
  .default = "Trump"))
```  


Day1 : Monday plotting data
#comment: # I do not quite understand the reason of dropping zero values
```{r}
#plotting trend
df  %>%  
  ggplot(aes(x = ym, y = report, color =  president), group_by = president) +
  geom_point() + geom_smooth(method = "lm", se = FALSE) +
  ylab("Report")  + 
  xlab("")


#plotting welfare
df  %>% 
  ggplot(aes(x = ym, y = welfare, color =  president), group_by = president) +
  geom_point() + geom_smooth(method = "lm", se = FALSE) +
  ylab("Welfare") + xlab("") + scale_y_continuous(limits = c(0, 100))

#plotting crime
df  %>% 
  ggplot(aes(x = ym, y = crime, color =  president), group_by = president) +
  geom_point() + geom_smooth(method = "lm", se = FALSE) +
  ylab("Crime") + xlab("") +
  labs(title = "2nd Graph") +
  scale_y_continuous(limits = c(0, 100))

```

#day 2 replicating Table 3
Crime regression
```{r}
df$president <- relevel(factor(df$president), ref = "Obama")
 
crime_regression <- lm(crime ~ ym + president, data = df)
summary(crime_regression)
```
#Regression for "Report"
```{r}
report_regression <- lm(report ~ ym + president, data = df)
summary(report_regression)
```

#Regression for "Welfare"
```{r}
welfare_regression <- lm(welfare ~ ym + president, data = df)
summary(welfare_regression)
```

#replicating Figure 2 and 3
starting with Topic model       
```{r}
library(stm)
load("TopicModel.RData")
document_topics <- make.dt(immigrFit, meta = out$meta)
topic_terms <- t(exp(immigrFit$beta$logbeta[[1]]))
rownames(topic_terms) <- out$vocab
colnames(topic_terms) <- sprintf("Topic%d", 1:ncol(topic_terms))
```

# Immigration news segments
```{r}
tot %>% 
  mutate( ym = ym(format(ymd(date), "%Y-%m"))) %>%
  group_by(channel, ym, post_election, post_trump, time ) %>% 
  summarize( total_duration = sum(duration)) %>%
  ggplot(aes(x = ym, y = total_duration, color = channel, group = interaction(channel, time))) +
  geom_point() + 
  geom_smooth( se = F) + 
  geom_vline(xintercept = c(ym("2015-06"), ym("2017-01")), linetype = "dashed")
```


#Immigration news segment by topic "Welfare"
```{r}
document_topics %>% 
  select(Topic13, channel, date, duration, post_election, post_trump, time) %>%
  mutate( ym = ym(format(ymd(date), "%Y-%m"))) %>%
  group_by(channel, ym, post_election, post_trump, time ) %>% 
  summarize( total_duration = sum(Topic13)) %>%
  ggplot(aes(x = ym, y = total_duration, color = channel, group = interaction(channel, time))) +
  geom_point() + 
  geom_smooth( se = F) + 
  geom_vline(xintercept = c(ym("2015-06"), ym("2017-01")), linetype = "dashed")+
  ylab("Immigr + Welfare \n News Coverage") +
  xlab("")
```
#Immigration segment by topic "Crime"
```{r}
document_topics %>% 
  select(Topic1, Topic3, channel, date, duration, post_election, post_trump, time) %>%  
  mutate(Topic  = Topic1 +  Topic3)%>% 
  mutate( ym = ym(format(ymd(date), "%Y-%m"))) %>%
  group_by(channel, ym, post_election, post_trump, time ) %>% 
  summarize( total_duration = sum(Topic)) %>%
  ggplot(aes(x = ym, y = total_duration, color = channel, group = interaction(channel, time))) +
  geom_point() + 
  geom_smooth( se = F) + 
  geom_vline(xintercept = c(ym("2015-06"), ym("2017-01")), linetype = "dashed") +
  ylab("Immigr + Crime \n News Coverage") +
  xlab("")
```





