---
title: "Test City bike Predictions"
author: "Sami"
date: "2024-06-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)
library(dplyr)
library(modelr)
library(scales)
# set plot theme
theme_set(theme_bw())
```

```{r}
load("trips_2015.RData")
# head(trips_2015)
```
```{r}
trips_2015 <- left_join(trips, weather, by = 'ymd')
head(trips_2015)
```

```{r}
# Provided data as a character string
data <- "1,2012-01-02,New Year Day
2,2012-01-16,Martin Luther King Jr. Day
3,2012-02-20,Presidents Day (Washingtons Birthday)
4,2012-05-28,Memorial Day
5,2012-07-04,Independence Day
6,2012-09-03,Labor Day
7,2012-10-08,Columbus Day
8,2012-11-12,Veterans Day
9,2012-11-22,Thanksgiving Day
10,2012-12-25,Christmas Day
11,2013-01-01,New Year Day
12,2013-01-21,Martin Luther King Jr. Day
13,2013-02-18,Presidents Day (Washingtons Birthday)
14,2013-05-27,Memorial Day
15,2013-07-04,Independence Day
16,2013-09-02,Labor Day
17,2013-10-14,Columbus Day
18,2013-11-11,Veterans Day
19,2013-11-28,Thanksgiving Day
20,2013-12-25,Christmas Day
21,2014-01-01,New Year Day
22,2014-01-20,Martin Luther King Jr. Day
23,2014-02-17,Presidents Day (Washingtons Birthday)
24,2014-05-26,Memorial Day
25,2014-07-04,Independence Day
26,2014-09-01,Labor Day
27,2014-10-13,Columbus Day
28,2014-11-11,Veterans Day
29,2014-11-27,Thanksgiving Day
30,2014-12-25,Christmas Day
31,2015-01-01,New Year Day
32,2015-01-19,Martin Luther King Jr. Day
33,2015-02-16,Presidents Day (Washingtons Birthday)
34,2015-05-25,Memorial Day
35,2015-07-03,Independence Day
36,2015-09-07,Labor Day
37,2015-10-12,Columbus Day
38,2015-11-11,Veterans Day
39,2015-11-26,Thanksgiving Day
40,2015-12-25,Christmas Day
41,2016-01-01,New Year Day
42,2016-01-18,Martin Luther King Jr. Day
43,2016-02-15,Presidents Day (Washingtons Birthday)
44,2016-05-30,Memorial Day
45,2016-07-04,Independence Day
46,2016-09-05,Labor Day
47,2016-10-10,Columbus Day
48,2016-11-11,Veterans Day
49,2016-11-24,Thanksgiving Day
50,2016-12-25,Christmas Day
51,2017-01-02,New Year Day
52,2017-01-16,Martin Luther King Jr. Day
53,2017-02-20,Presidents Day (Washingtons Birthday)
54,2017-05-29,Memorial Day
55,2017-07-04,Independence Day
56,2017-09-04,Labor Day
57,2017-10-09,Columbus Day
58,2017-11-10,Veterans Day
59,2017-11-23,Thanksgiving Day
60,2017-12-25,Christmas Day
61,2018-01-01,New Year Day
62,2018-01-15,Martin Luther King Jr. Day
63,2018-02-19,Presidents Day (Washingtons Birthday)
64,2018-05-28,Memorial Day
65,2018-07-04,Independence Day
66,2018-09-03,Labor Day
67,2018-10-08,Columbus Day
68,2018-11-12,Veterans Day
69,2018-11-22,Thanksgiving Day
70,2018-12-25,Christmas Day
71,2019-01-01,New Year Day
72,2019-01-21,Martin Luther King Jr. Day
73,2019-02-18,Presidents Day (Washingtons Birthday)
74,2019-05-27,Memorial Day
75,2019-07-04,Independence Day
76,2019-09-02,Labor Day
77,2019-10-14,Columbus Day
78,2019-11-11,Veterans Day
79,2019-11-28,Thanksgiving Day
80,2019-12-25,Christmas Day
81,2020-01-01,New Year Day
82,2020-01-20,Martin Luther King Jr. Day
83,2020-02-17,Presidents Day (Washingtons Birthday)
84,2020-05-25,Memorial Day
85,2020-07-03,Independence Day
86,2020-09-07,Labor Day
87,2020-10-12,Columbus Day
88,2020-11-11,Veterans Day
89,2020-11-26,Thanksgiving Day
90,2020-12-25,Christmas Day"

# Read the data into a data frame
holiday_data <- read.csv(text = data, header = FALSE, col.names = c("serial", "date", "holiday"))

# Print the data frame to verify
print(holiday_data)

# Write the data frame to a CSV file
write.csv(holiday_data, "holidays.csv", row.names = FALSE)

# Confirm that the file has been written
cat("The holidays.csv file has been created successfully.")

head(holiday_data)
```
```{r}
trips_2015 <- trips_2015 |>
  mutate(tmax = tmax/10, tmin = tmin/10)

head(trips_2015)
```

```{r}
trip_per_day_2015 <- 
  trips_2015 |>
  mutate(day_of_week = weekdays(ymd)) |>
  mutate(is_weekend = ifelse(day_of_week %in% c("Saturday","Sunday"), TRUE, FALSE)) |>
  mutate(is_holiday = ifelse(ymd %in% holiday_data$date, TRUE, FALSE)) |>
  mutate(tavg = (tmax + tmin)/2) |>
  select(ymd, date, prcp, snwd, snow, tavg, tmax, tmin, is_weekend, is_holiday)

head(trip_per_day_2015)
```
```{r}
trip_per_day_2015 <- 
  trip_per_day_2015 |>
  group_by(ymd, prcp, snwd, snow, tavg, tmax, tmin, is_weekend, is_holiday) |>
  summarise(num_trips = n()) |> view()

  
```
```{r}
load("~/coursework/week3/model_test.RData")
ls()
```


# Testing model on the test data
```{r}

rmse_test <- sqrt(mean((predict(model_test, trip_per_day_2015) - trip_per_day_2015$num_trips)^2, na.rm = TRUE))

rmse_test
```
```{r}
```


```{r}
trip_per_day_prediction_test <- 
  add_predictions(trip_per_day_2015, model_test, var = "pred", type = NULL)

  
trip_per_day_prediction_test |>
  ggplot() +
  geom_point( aes(x = ymd, y = num_trips, colour = "red")) +
  geom_line(aes(x = ymd, y = preds))
  
```
```{r}
# create predict vs actual result graph using test data
trip_per_day_prediction_test |>
  ggplot(aes(x =  preds, y = num_trips)) +
  geom_point() +
  geom_abline(linetype = 'dashed') +
  xlab("Predicted")+
  ylab("Actual")
```
