---
title: "Working With RStudio Server"
author: "Coen D. Needell (SoyBison)"
date: "6/21/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Using Git on RStudio Server (pre 1.1)

The version of RStudio Server we are using does not have the Terminal Emulator tab like your desktop versions has.
This can make it difficult to manage our GitHub repos.
There is, however a rudimentary shell built into RStudio. 
In Tools -> Shell..., there is a drop-down terminal emulator. It doesn't support advanced features like tab completion, nor can you use any shells besides `bash`.
You will need to set up a new ssh key for your account on the server.

First, go to Tools -> Shell... and open a new terminal.
You will need to generate a new SSH key.

```bash
ssh-keygen
```

Then you need to get the public key, and attach it to your GitHub account.
First, get the public key.

```bash
cat ~/.ssh/id_rsa.pub
```

Copy the output to your clipboard.
You can't use `xclip` for this, so you will have to highlight the key in-browser and do Ctrl+C or right click -> copy.
Next, go to [https://github.com/settings/keys](https://github.com/settings/keys) in a web browser.
You will need to log into GitHub if you haven't.
Click the green "New SSH Key" button in the upper right.
Name this key whatever you want. (Mine is called "rstud server.")
You should now be able to log into GitHub with no prompt from the server.
Git cloning, committing, and pushing all should work normally.

You will also need to set a Git identity, you will be prompted about it when you try to commit something.
You just need to provide git with some sort of identification to attach to your commit, and it's general practice to use the same information you have on your GitHub account.

You can do this with:

```bash
git config --global user.email "l33th4x0r@macrohard.com"
git config --global user.name "xXx_l33th4x0r_XxX"
```
You will of course replace the strings with your email and username.
