---
title: "predict_citibike"
author: "Shana Mandelbaum"
date: "2024-06-21"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(scales)
library(tidyverse)
library(modelr)
library(lubridate)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)
```

## Load the data
```{r}
trips_per_day <- read_tsv("trips_per_day.tsv")
```

## Create is_weekend and is_holiday columns
```{r}
data <- "1,2012-01-02,New Year Day
2,2012-01-16,Martin Luther King Jr. Day
3,2012-02-20,Presidents Day (Washingtons Birthday)
4,2012-05-28,Memorial Day
5,2012-07-04,Independence Day
6,2012-09-03,Labor Day
7,2012-10-08,Columbus Day
8,2012-11-12,Veterans Day
9,2012-11-22,Thanksgiving Day
10,2012-12-25,Christmas Day
11,2013-01-01,New Year Day
12,2013-01-21,Martin Luther King Jr. Day
13,2013-02-18,Presidents Day (Washingtons Birthday)
14,2013-05-27,Memorial Day
15,2013-07-04,Independence Day
16,2013-09-02,Labor Day
17,2013-10-14,Columbus Day
18,2013-11-11,Veterans Day
19,2013-11-28,Thanksgiving Day
20,2013-12-25,Christmas Day
21,2014-01-01,New Year Day
22,2014-01-20,Martin Luther King Jr. Day
23,2014-02-17,Presidents Day (Washingtons Birthday)
24,2014-05-26,Memorial Day
25,2014-07-04,Independence Day
26,2014-09-01,Labor Day
27,2014-10-13,Columbus Day
28,2014-11-11,Veterans Day
29,2014-11-27,Thanksgiving Day
30,2014-12-25,Christmas Day
31,2015-01-01,New Year Day
32,2015-01-19,Martin Luther King Jr. Day
33,2015-02-16,Presidents Day (Washingtons Birthday)
34,2015-05-25,Memorial Day
35,2015-07-03,Independence Day
36,2015-09-07,Labor Day
37,2015-10-12,Columbus Day
38,2015-11-11,Veterans Day
39,2015-11-26,Thanksgiving Day
40,2015-12-25,Christmas Day
41,2016-01-01,New Year Day
42,2016-01-18,Martin Luther King Jr. Day
43,2016-02-15,Presidents Day (Washingtons Birthday)
44,2016-05-30,Memorial Day
45,2016-07-04,Independence Day
46,2016-09-05,Labor Day
47,2016-10-10,Columbus Day
48,2016-11-11,Veterans Day
49,2016-11-24,Thanksgiving Day
50,2016-12-25,Christmas Day
51,2017-01-02,New Year Day
52,2017-01-16,Martin Luther King Jr. Day
53,2017-02-20,Presidents Day (Washingtons Birthday)
54,2017-05-29,Memorial Day
55,2017-07-04,Independence Day
56,2017-09-04,Labor Day
57,2017-10-09,Columbus Day
58,2017-11-10,Veterans Day
59,2017-11-23,Thanksgiving Day
60,2017-12-25,Christmas Day
61,2018-01-01,New Year Day
62,2018-01-15,Martin Luther King Jr. Day
63,2018-02-19,Presidents Day (Washingtons Birthday)
64,2018-05-28,Memorial Day
65,2018-07-04,Independence Day
66,2018-09-03,Labor Day
67,2018-10-08,Columbus Day
68,2018-11-12,Veterans Day
69,2018-11-22,Thanksgiving Day
70,2018-12-25,Christmas Day
71,2019-01-01,New Year Day
72,2019-01-21,Martin Luther King Jr. Day
73,2019-02-18,Presidents Day (Washingtons Birthday)
74,2019-05-27,Memorial Day
75,2019-07-04,Independence Day
76,2019-09-02,Labor Day
77,2019-10-14,Columbus Day
78,2019-11-11,Veterans Day
79,2019-11-28,Thanksgiving Day
80,2019-12-25,Christmas Day
81,2020-01-01,New Year Day
82,2020-01-20,Martin Luther King Jr. Day
83,2020-02-17,Presidents Day (Washingtons Birthday)
84,2020-05-25,Memorial Day
85,2020-07-03,Independence Day
86,2020-09-07,Labor Day
87,2020-10-12,Columbus Day
88,2020-11-11,Veterans Day
89,2020-11-26,Thanksgiving Day
90,2020-12-25,Christmas Day"

holidays <- read.csv(text = data, header = FALSE, 
                     col.names = c("id", "date", "holiday"))

trips_per_day <- trips_per_day|> 
  mutate(day_of_week = wday(ymd, label = TRUE)) |> 
  mutate(is_weekend = (day_of_week == "Sat" | 
                         day_of_week == "Sun")) |> 
  mutate(is_holiday = ifelse(ymd %in% holidays$date, TRUE, FALSE)) |> 
  mutate(avg_temp = (tmin + tmax)/2)
```
## Split into train and test data
```{r}
set.seed(42)
num_days <- nrow(trips_per_day)
frac_test <- .1
num_test <- floor(num_days * frac_test)
ndx <- sample(1:num_days, num_test)
trips_per_day_test <- trips_per_day[ndx, ]
trips_per_day_train <- trips_per_day[-ndx, ]
```

## Plot data to look for patterns
```{r}
trips_per_day_train |> 
  ggplot(aes(x = tmin, y = num_trips)) +
  geom_point()

trips_per_day_train |> 
  ggplot(aes(x = avg_temp, y = num_trips)) +
  geom_point()

trips_per_day_train |> 
  ggplot(aes(x = avg_temp, y = num_trips, color = is_weekend)) +
  geom_point()

trips_per_day_train |> 
  ggplot(aes(x = tmin, y = num_trips, color = is_holiday)) +
  geom_point()
trips_per_day_train |> 
  ggplot(aes(x = ymd, y = tmin)) +
  geom_point()
```


```{r}
num_folds <- 5

trips_per_day_train <- trips_per_day_train |> 
  mutate(fold = (row_number() %% num_folds) + 1)

K <- 1:8
avg_validate_err <- c()
se_validate_err <- c()

for (k in K) {
  validate_err <- c()
  for (f in 1:num_folds) {
    trip_per_day_model_train <- filter(trips_per_day_train, fold != f)
    model <- lm(num_trips ~ poly(avg_temp, k, raw = T), 
                data = trip_per_day_model_train)
    
    trips_per_day_validate <- filter(trips_per_day_train, fold == f)
    validate_err[f] <- sqrt(mean((predict(model, trips_per_day_validate)
                                  - trips_per_day_validate$num_trips)^2))
  }
  avg_validate_err[k] <- mean(validate_err)
  se_validate_err[k] <- sd(validate_err)/sqrt(num_folds)
}

plot_data <- data.frame(K, avg_validate_err, se_validate_err)
ggplot(plot_data, aes(x=K, y=avg_validate_err)) +
  geom_pointrange(aes(ymin=avg_validate_err - se_validate_err,
                      ymax=avg_validate_err + se_validate_err,
                      color=avg_validate_err == min(avg_validate_err))) +
  geom_line(color = "red") +
  scale_x_continuous(breaks=1:12) +
  theme(legend.position="none") +
  xlab('Polynomial Degree') +
  ylab('RMSE on validation data')
```
```{r}
model1 <- lm(num_trips ~ poly(avg_temp, 6, raw = T), data = trips_per_day_train)
summary(model1)
```
```{r}
for (k in K) {
  validate_err <- c()
  for (f in 1:num_folds) {
    trip_per_day_model_train <- filter(trips_per_day_train, fold != f)
    model <- lm(num_trips ~ poly(avg_temp, k, raw = T)*I(prcp >0), 
                data = trip_per_day_model_train)
    
    trips_per_day_validate <- filter(trips_per_day_train, fold == f)
    validate_err[f] <- sqrt(mean((predict(model, trips_per_day_validate)
                                  - trips_per_day_validate$num_trips)^2))
  }
  avg_validate_err[k] <- mean(validate_err)
  se_validate_err[k] <- sd(validate_err)/sqrt(num_folds)
}

plot_data <- data.frame(K, avg_validate_err, se_validate_err)
ggplot(plot_data, aes(x=K, y=avg_validate_err)) +
  geom_pointrange(aes(ymin=avg_validate_err - se_validate_err,
                      ymax=avg_validate_err + se_validate_err,
                      color=avg_validate_err == min(avg_validate_err))) +
  geom_line(color = "red") +
  scale_x_continuous(breaks=1:12) +
  theme(legend.position="none") +
  xlab('Polynomial Degree') +
  ylab('RMSE on validation data')
```
```{r}
model2 <- lm(num_trips ~ poly(avg_temp, 5, raw = T)*I(prcp >0),
             data = trips_per_day_train)
summary(model2)
```
```{r}
for (k in K) {
  validate_err <- c()
  for (f in 1:num_folds) {
    trip_per_day_model_train <- filter(trips_per_day_train, fold != f)
    model <- lm(num_trips ~ poly(avg_temp, k, raw = T)*I(prcp >0) + is_weekend, 
                data = trip_per_day_model_train)
    
    trips_per_day_validate <- filter(trips_per_day_train, fold == f)
    validate_err[f] <- sqrt(mean((predict(model, trips_per_day_validate)
                                  - trips_per_day_validate$num_trips)^2))
  }
  avg_validate_err[k] <- mean(validate_err)
  se_validate_err[k] <- sd(validate_err)/sqrt(num_folds)
}

plot_data <- data.frame(K, avg_validate_err, se_validate_err)
ggplot(plot_data, aes(x=K, y=avg_validate_err)) +
  geom_pointrange(aes(ymin=avg_validate_err - se_validate_err,
                      ymax=avg_validate_err + se_validate_err,
                      color=avg_validate_err == min(avg_validate_err))) +
  geom_line(color = "red") +
  scale_x_continuous(breaks=1:12) +
  theme(legend.position="none") +
  xlab('Polynomial Degree') +
  ylab('RMSE on validation data')
```
```{r}
model3 <- lm(num_trips ~ poly(avg_temp, 4, raw = T)*I(prcp >0) + is_weekend,
             data = trips_per_day_train)
summary(model3)
```
```{r}
for (k in K) {
  validate_err <- c()
  for (f in 1:num_folds) {
    trip_per_day_model_train <- filter(trips_per_day_train, fold != f)
    model <- lm(num_trips ~ poly(avg_temp, k, raw = T)*prcp + is_weekend + is_holiday,
                data = trip_per_day_model_train)
    
    trips_per_day_validate <- filter(trips_per_day_train, fold == f)
    validate_err[f] <- sqrt(mean((predict(model, trips_per_day_validate)
                                  - trips_per_day_validate$num_trips)^2))
  }
  avg_validate_err[k] <- mean(validate_err)
  se_validate_err[k] <- sd(validate_err)/sqrt(num_folds)
}

plot_data <- data.frame(K, avg_validate_err, se_validate_err)
ggplot(plot_data, aes(x=K, y=avg_validate_err)) +
  geom_pointrange(aes(ymin=avg_validate_err - se_validate_err,
                      ymax=avg_validate_err + se_validate_err,
                      color=avg_validate_err == min(avg_validate_err))) +
  geom_line(color = "red") +
  scale_x_continuous(breaks=1:12) +
  theme(legend.position="none") +
  xlab('Polynomial Degree') +
  ylab('RMSE on validation data')
```

```{r}
model4 <- lm(num_trips ~ poly(avg_temp, 5, raw = T)*prcp + is_weekend + is_holiday,
             data = trips_per_day_train)
summary(model4)
```

```{r}
for (k in K) {
  validate_err <- c()
  for (f in 1:num_folds) {
    trip_per_day_model_train <- filter(trips_per_day_train, fold != f)
    model <- lm(num_trips ~ poly(avg_temp, k, raw = T)*I(prcp >0) + is_weekend + snwd, 
                data = trip_per_day_model_train)
    
    trips_per_day_validate <- filter(trips_per_day_train, fold == f)
    validate_err[f] <- sqrt(mean((predict(model, trips_per_day_validate)
                                  - trips_per_day_validate$num_trips)^2))
  }
  avg_validate_err[k] <- mean(validate_err)
  se_validate_err[k] <- sd(validate_err)/sqrt(num_folds)
}

plot_data <- data.frame(K, avg_validate_err, se_validate_err)
ggplot(plot_data, aes(x=K, y=avg_validate_err)) +
  geom_pointrange(aes(ymin=avg_validate_err - se_validate_err,
                      ymax=avg_validate_err + se_validate_err,
                      color=avg_validate_err == min(avg_validate_err))) +
  geom_line(color = "red") +
  scale_x_continuous(breaks=1:12) +
  theme(legend.position="none") +
  xlab('Polynomial Degree') +
  ylab('RMSE on validation data')
```



```{r}
trips_per_day_train |> 
  mutate(preds = predict(model4, trips_per_day_train)) |>
  ggplot(aes(x = preds, y = num_trips)) +
  geom_point() +
  geom_abline(linetype = "dashed") +
  xlab('Predicted') +
  ylab('Actual')
```

```{r}
trips_per_day_train_preds <- trips_per_day_train |> 
  mutate(preds = predict(model4, trips_per_day_train))

trips_per_day_train_preds |> 
  ggplot() +
  geom_point(aes(x = ymd, y = num_trips, color = "red")) +
  geom_line(aes(x = ymd, y = preds))
```

```{r}
save(model4, file = "final_model.RData")
```

```{r}
Test_RMSE<- sqrt(mean((predict(model4, trips_per_day_test) - trips_per_day_test$num_trips)^2))
Test_RMSE 
```

