---
title: "Citibike Prediction"
output: html_document
date: '2022-06-16'
---

```{r}
library(tidyverse)
library(scales)
library(modelr)
library(lubridate)

```
```{r}
trips_per_day <- read_tsv('trips_per_day.tsv') 
trips_per_day <- trips_per_day%>%
  mutate(day = wday(ymd))%>%
  mutate(weekday = ifelse(day==6|day==7, 0, 1)) %>%
  mutate(rainy = (prcp >= 0.5))

holidays <- read_csv("holidays.csv", col_names = c('sr','ymd','name')) %>% select(ymd) %>% mutate(holiday=1)

trips_per_day <- left_join(trips_per_day, holidays, by="ymd") %>% mutate(holiday = ifelse(is.na(holiday), 0, 1))
```


```{r}
set.seed(42)

num_days <- nrow(trips_per_day)
frac_train_valid <- 0.9
num_train_valid <- floor(num_days * frac_train_valid)
#randomly sample rows for training and validating
ndx <- sample(1:num_days, num_train_valid, replace=F)
# used to fit the model
trips_per_day_train_valid <- trips_per_day[ndx, ]
# used to evaluate  and the fit
trips_per_day_test <- trips_per_day[-ndx, ]

```
#
```{r}
num_date <- nrow(trips_per_day_train_valid)
frac_train <- 0.8
num_train <- floor(num_date * frac_train)

# randomly sample rows for  training
ndv<- sample(1:num_date, num_train, replace=F)
# used to fit the model
trips_per_day_train <- trips_per_day_train_valid[ndv, ]

# used to evaluate the fit
trips_per_day_valid <- trips_per_day_train_valid[-ndv, ]


```

```{r}
K <- 1:8
train_err <- c()
validate_err <- c()
for (k in K) {
  
    # fit on the training data
    model <- lm(num_trips ~ poly(tmin, k, raw = T), data = trips_per_day_train)
    
    # evaluate on the training data
    train_err[k] <- sqrt(mean((predict(model, trips_per_day_train) - trips_per_day_train$num_trips)^2))

    # evaluate on the validate data
    validate_err[k] <- sqrt(mean((predict(model, trips_per_day_valid) - trips_per_day_valid$num_trips)^2))
}
```

```{r}
plot_data <- data.frame(K, train_err, validate_err) %>%
  gather("split", "error", -K)

ggplot(plot_data, aes(x=K, y=error, color=split)) +
  geom_line() +
  scale_x_continuous(breaks=K) +
  xlab('Polynomial Degree') +
  ylab('RMSE')
```
```{r}
model <- lm(num_trips ~ poly(tmin, 4, raw = T), data = trips_per_day_train)

trips_per_day_train <- trips_per_day_train%>%
  add_predictions(model) %>%
  mutate(split = "train")
trips_per_day_valid <- trips_per_day_valid %>%
  add_predictions(model) %>%
  mutate(split = "validate")
plot_data <- bind_rows(train_trips,validate_trips)

ggplot(plot_data, aes(x = tmin, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Minimum temperature') +
  ylab('Daily trips') +
  scale_y_continuous()
```

```{r}
model<- lm(formula = num_trips ~ poly(tmin, 4, raw = T) + holiday + snwd + prcp + snow + rainy + weekday + poly(tmax, 4, raw = T), data = trips_per_day_train)

trips_per_day_train <- trips_per_day_train%>%
  add_predictions(model) %>%
  mutate(split = "train")
trips_per_day_valid <- trips_per_day_valid %>%
  add_predictions(model) %>%
  mutate(split = "validate")

summary(model)
```

```{r}
rsquare(model,trips_per_day_train)
rmse(model,trips_per_day_train)
rsquare(model,trips_per_day_valid)
rmse(model,trips_per_day_valid)
```

```{r}
plot_data <- bind_rows(trips_per_day_train, trips_per_day_valid)

ggplot(plot_data, aes(x = pred, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Minimum temperature') +
  ylab('Daily trips') +
  scale_y_continuous()
```
```{r}
plot_data <- bind_rows(trips_per_day_train, trips_per_day_valid)

ggplot(plot_data, aes(x = ymd, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Date') +
  ylab('Actual Trips') +
  scale_y_continuous()

ggplot(plot_data, aes(x = pred, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Predicted Trips') +
  ylab('Actual Trips') +
  scale_y_continuous()
```

```{r}
final_model <- lm(formula = num_trips ~ poly(tmin, 4, raw = T) + holiday + snwd + prcp + snow + rainy + weekday + poly(tmax, 4, raw = T), data = trips_per_day_train)

rsquare(final_model, trips_per_day_test)
rmse(final_model, trips_per_day_test)

trips_per_day_test <- trips_per_day_test %>%
  add_predictions(final_model) %>%
  mutate(split = "test")
```


```{r}
plot_data <- bind_rows(trips_per_day_train, trips_per_day_valid, trips_per_day_test)

ggplot(plot_data, aes(x = ymd, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Date') +
  ylab('Actual Trips') +
  scale_y_continuous()

ggplot(plot_data, aes(x = pred, y = num_trips)) +
  geom_point(aes(color = split)) +
  geom_line(aes(y = pred)) +
  xlab('Predicted Trips') +
  ylab('Actual Trips') +
  scale_y_continuous()
```